[project]
name = "paper-summary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arxiv>=2.1.3",
    "beautifulsoup4>=4.13.3",
    "ipykernel>=6.29.5",
    "pydantic>=2.11.1",
    "pypdf>=5.4.0",
]
